apiVersion: v1
kind: PersistentVolume
metadata:
  name: vault-pv
  labels:
    app: vault
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: vault-storage
  hostPath:
    path: /mnt/data/vault
